name: Daily Report

on:
  schedule:
    - cron: "00 10 * * *"
  workflow_dispatch:
    inputs:
      mode:
        description: "Select sending mode"
        required: false
        type: choice
        options:        
          - one
          - many
          - all
        default: ""
      emails:
        description: "Comma-separated emails for mode=one or mode=many"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python report_parent.py
        env:
          RECIPIENTS_JSON: ${{ secrets.RECIPIENTS_JSON }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

          MODE: ${{ github.event.inputs.mode }}
          EMAILS: ${{ github.event.inputs.emails }}

          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}

          # Add as many API_X_URL as you need:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          # API_4_URL: ${{ secrets.API_4_URL }}
          # API_5_URL: ${{ secrets.API_5_URL }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: run.log
