name: Weekly Report

on:
  schedule:
    - cron: "30 19 * * SAT"
  workflow_dispatch:

jobs:
  run_weekly:
    uses: ./.github/workflows/daily-report.yml
    with:
      mode: ""   # or pass empty to default
      emails: ""
    secrets: inherit
